[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
algorithms = { path = "../algorithms" }  
shared = { path = "../shared" }
serde = { workspace = true }
serde_json = { workspace = true }

